#pragma once
#include <Arduino.h>

const char ADMIN_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="zh-CN"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Traveler Weather Clock</title>
<style>
:root{--blue:#2f80ed;--sky:#69b7ff;--ink:#102d48;--muted:#71859a;--line:#dce8f2;--card:rgba(255,255,255,.82);--glass:rgba(255,255,255,.66);--green:#38c981;--red:#ef6872;--warm:#ffb84d;--shadow:0 18px 46px rgba(38,91,132,.13)}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:linear-gradient(155deg,#eaf6ff 0%,#f8fbff 42%,#eef7ff 100%);min-height:100vh}body:before{content:"";position:fixed;inset:0;background:radial-gradient(circle at 10% 10%,rgba(255,255,255,.95),transparent 28%),radial-gradient(circle at 80% 4%,rgba(47,128,237,.22),transparent 35%),radial-gradient(circle at 70% 86%,rgba(255,194,82,.18),transparent 36%);pointer-events:none}.app{position:relative;max-width:430px;margin:auto;min-height:100vh;padding:12px 12px 84px}.top{position:sticky;top:0;z-index:6;margin:0 -12px 12px;padding:12px 14px 10px;background:rgba(255,255,255,.74);backdrop-filter:blur(20px);border-bottom:1px solid rgba(163,188,210,.32);display:flex;align-items:center;gap:9px}.logo{font-size:25px;filter:drop-shadow(0 4px 8px rgba(47,128,237,.22))}.title{font-weight:900;letter-spacing:-.3px}.sub{font-size:12px;color:var(--muted);margin-top:1px}.menu{margin-left:auto;font-size:24px;color:#173b5c}
.nav{position:fixed;z-index:9;left:50%;bottom:12px;transform:translateX(-50%);width:min(410px,calc(100vw - 24px));height:61px;background:rgba(255,255,255,.86);backdrop-filter:blur(22px);border:1px solid rgba(174,194,212,.62);border-radius:22px;display:grid;grid-template-columns:repeat(7,1fr);box-shadow:0 18px 42px rgba(43,95,132,.16)}.nav button{border:0;background:transparent;color:#60768b;font-size:10px;font-weight:800}.nav span{display:block;font-size:19px;margin-bottom:2px}.nav .on{color:var(--blue)}
.card{background:var(--card);backdrop-filter:blur(20px);border:1px solid rgba(174,194,212,.48);box-shadow:var(--shadow);border-radius:20px;padding:15px;margin:11px 0}.card h2{font-size:16px;margin:0 0 10px;letter-spacing:-.2px}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-top:1px solid rgba(216,228,240,.75)}.row:first-child{border-top:0}.muted{color:var(--muted);font-size:12px}.big{font-size:35px;font-weight:900;letter-spacing:-1.4px}.ok{color:var(--green)}.bad{color:var(--red)}.tag{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;background:#eaf4ff;color:#2670bb;font-size:12px;font-weight:800}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:9px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.btn,button{appearance:none;border:1px solid var(--line);background:white;color:#1b4f82;border-radius:13px;padding:10px 12px;font-weight:850}.primary,.btn.primary{background:linear-gradient(135deg,#55a5ff,#2f80ed);color:white;border:0;box-shadow:0 9px 20px rgba(47,128,237,.24)}.danger{color:#d94d55;border-color:#ffc9ce}
.startup{padding:0;overflow:hidden;background:#061023}.startup img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.hero{overflow:hidden;border-radius:22px;padding:16px;color:white;background:linear-gradient(135deg,rgba(40,144,235,.94),rgba(22,67,128,.92));box-shadow:0 18px 44px rgba(45,117,182,.22);position:relative}.hero:before{content:"";position:absolute;right:-16px;top:-18px;width:150px;height:120px;background:radial-gradient(circle,#fff .8px,transparent 1px);background-size:17px 17px;opacity:.42}.hero h1{font-size:52px;margin:8px 0 0;letter-spacing:-2px}.hero small{font-size:15px}.hero-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:13px}.hero-grid div{background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:9px;font-size:12px}.hero-grid b{display:block;font-size:15px;margin-top:3px}
.tabs{display:flex;background:rgba(255,255,255,.9);border:1px solid var(--line);border-radius:15px;padding:4px;margin:4px 0 10px;gap:4px}.tabs button{flex:1;border:0;border-radius:11px;background:transparent;color:#31506a;padding:8px 3px;font-size:12px}.tabs .on{background:linear-gradient(135deg,#52a1ff,#2f80ed);color:white}.mini{height:90px;width:100%}.forecast{display:grid;grid-template-columns:42px 1fr 42px 42px 44px;gap:8px;align-items:center;font-size:13px;padding:8px 0;border-top:1px solid rgba(216,228,240,.65)}.forecast:first-child{border-top:0}
.scene,.outfit,.tone{min-height:90px;text-align:center;background:linear-gradient(155deg,#eef8ff,#fff);border:1px solid var(--line);border-radius:16px;padding:10px 6px;box-shadow:0 8px 18px rgba(47,128,237,.06)}.scene .pic{height:48px;border-radius:12px;margin-bottom:8px;position:relative;overflow:hidden}.pic:after{content:"";position:absolute;inset:0;background:linear-gradient(160deg,rgba(255,255,255,.28),transparent 52%)}.sun .pic{background:linear-gradient(135deg,#8fd0ff,#ffe69a)}.cloud .pic{background:linear-gradient(135deg,#9ed7ff,#dceaf7)}.rain .pic{background:linear-gradient(135deg,#637a96,#203b62)}.snow .pic{background:linear-gradient(135deg,#e7fbff,#9ab9d8)}.night .pic{background:linear-gradient(135deg,#081b48,#743fb4)}.typhoon .pic{background:linear-gradient(135deg,#3a4655,#0f1d34)}.random .pic{background:linear-gradient(135deg,#ffa63d,#6d7cff)}.live .pic{background:linear-gradient(135deg,#4dcf8e,#67b7ff)}.on{outline:2px solid var(--blue)}
.person{font-size:34px}.dogface{font-size:32px}.tone i{display:block;width:34px;height:34px;border-radius:50%;margin:5px auto 8px;box-shadow:inset -8px -8px 16px rgba(0,0,0,.08),0 3px 10px rgba(30,60,90,.1)}.range{display:grid;grid-template-columns:92px 1fr 46px;gap:10px;align-items:center;padding:10px 0;border-top:1px solid rgba(216,228,240,.75)}input,select{width:100%;border:1px solid var(--line);border-radius:13px;background:white;padding:11px;color:var(--ink);font-size:15px}input[type=range]{padding:0;accent-color:var(--blue)}.switch{display:flex;align-items:center;justify-content:space-between;gap:12px}.switch input{display:none}.slider{width:48px;height:27px;border-radius:99px;background:#cbd8e2;position:relative;transition:.2s}.slider:after{content:"";position:absolute;width:23px;height:23px;left:2px;top:2px;border-radius:50%;background:white;box-shadow:0 2px 8px rgba(0,0,0,.18);transition:.2s}.switch input:checked+.slider{background:var(--green)}.switch input:checked+.slider:after{transform:translateX(21px)}
.colors{display:flex;gap:12px;flex-wrap:wrap}.dot{width:25px;height:25px;border-radius:999px;border:2px solid white;box-shadow:0 0 0 1px var(--line)}.hint{background:linear-gradient(135deg,#f4faff,#fff);border:1px dashed #bed3e6;border-radius:15px;padding:11px;color:#557089;font-size:12px;line-height:1.5}
</style></head><body><main class="app"><header class="top"><div class="logo">🌤️</div><div><div class="title">Traveler Clock</div><div class="sub" id="ip">正在连接设备…</div></div><div class="menu">☰</div></header><section id="view"></section></main><nav class="nav" id="nav"></nav>
<script>
let S=null,tab='home',roleTab='traveler';
const nav=[['home','⌂','概览'],['weather','☁️','天气'],['role','🚴','角色'],['status','▣','状态栏'],['settings','⚙️','设置'],['wifi','⌁','Wi‑Fi'],['about','ⓘ','关于']];
const scenes=[['live','实时','live','恢复当前网络天气'],['sunny','晴天','sun','太阳与小鸟出现'],['cloudy','多云','cloud','柔和天空和云层'],['rain','雨天','rain','雨衣和降雨动画'],['snow','雪天','snow','雪花和冬装'],['night','夜晚露营','night','帐篷休息'],['typhoon','台风','typhoon','强风暴雨'],['random','随机','random','随机天气组合']];
const outfits=[['0','短袖','🧍'],['1','衬衫','🚶'],['2','毛衣','🧥'],['3','夹克','🧍‍♂️'],['4','大衣','🕴️'],['5','雨衣','🌧️']];
const dogTones=[['0','雪白','#ffffff'],['1','暖白','#fff3d8'],['2','奶油','#f7dea2'],['3','冷白','#e7fbff'],['4','银灰','#bfc8cc']];
function q(x){return document.querySelector(x)}function esc(x){return String(x??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function api(path,body){let opt={cache:'no-store'};if(body){opt.method='POST';opt.headers={'Content-Type':'application/x-www-form-urlencoded'};opt.body=new URLSearchParams(body)}let r=await fetch(path,opt);return await r.json()}
async function load(){try{S=await api('/api/status');q('#ip').textContent=S.wifi.connected?`${S.wifi.ip} · ${S.wifi.ssid}`:'设备未联网';render()}catch(e){q('#view').innerHTML='<div class=card><h2>无法连接设备</h2><p class=muted>页面已打开，但状态接口读取失败。请刷新，或确认手机仍在同一 Wi‑Fi。</p></div>'}}
function save(o){api('/api/settings',o).then(load)}function demo(scene){api('/api/demo',{scene}).then(load)}function refreshWeather(){api('/api/refresh',{}).then(load)}function reboot(){if(confirm('确定重启设备？'))api('/api/reboot',{}).then(()=>alert('设备正在重启'))}
function renderNav(){q('#nav').innerHTML=nav.map(n=>`<button class="${tab==n[0]?'on':''}" onclick="tab='${n[0]}';render()"><span>${n[1]}</span>${n[2]}</button>`).join('')}
function render(){renderNav();if(!S)return;({home,weather,role,status,settings,wifi,about}[tab])();window.scrollTo(0,0)}
function sw(k,t,v,sub=''){return `<label class="row switch"><span><b>${t}</b>${sub?`<br><small class=muted>${sub}</small>`:''}</span><input type=checkbox ${v?'checked':''} onchange="save({${k}:this.checked?1:0})"><i class=slider></i></label>`}
function range(k,t,v,min,max,unit='%'){return `<div class=range><b>${t}</b><input type=range min=${min} max=${max} value=${v} oninput="this.nextElementSibling.textContent=this.value+'${unit}'" onchange="save({${k}:this.value})"><span class=tag>${v}${unit}</span></div>`}
function drawChart(id,arr){setTimeout(()=>{let c=q('#'+id);if(!c||!arr)return;let d=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.clientHeight*2;d.clearRect(0,0,w,h);d.strokeStyle='#dbe8f4';d.lineWidth=1;for(let i=1;i<4;i++){d.beginPath();d.moveTo(0,h*i/4);d.lineTo(w,h*i/4);d.stroke()}d.fillStyle='rgba(67,151,238,.18)';d.strokeStyle='#2f80ed';d.lineWidth=4;d.beginPath();arr.forEach((v,i)=>{let x=i/(arr.length-1)*w,y=h-(v/100)*(h-14)-7;i?d.lineTo(x,y):d.moveTo(x,y)});d.stroke();d.lineTo(w,h);d.lineTo(0,h);d.closePath();d.fill();let now=new Date(),x=(now.getHours()*60+now.getMinutes())/1439*w;d.strokeStyle='#102d48';d.lineWidth=2;d.beginPath();d.moveTo(x,0);d.lineTo(x,h);d.stroke()},20)}
function home(){let w=S.weather;q('#view').innerHTML=`<div class="card startup"><img src="/startup.bmp?v=1" alt="startup"></div><div class=hero><span class=tag>📍 ${esc(S.location)} · ${S.mode=='demo'?'预览模式':'实时天气'}</span><h1>${w.valid?Math.round(w.temp):'--'}<small>°C</small></h1><b>${esc(w.label||'天气获取中')}</b><div class=hero-grid><div>体感<b>${Math.round(w.feels)}°C</b></div><div>云量<b>${Math.round(w.cloud)}%</b></div><div>风速<b>${w.wind.toFixed(1)}m/s</b></div></div></div><div class=card><h2>未来 24 小时降水概率</h2><canvas id=rain class=mini></canvas></div><div class=grid3><div class=card><div class=muted>日出</div><b>${S.sunrise}</b></div><div class=card><div class=muted>日落</div><b>${S.sunset}</b></div><div class=card><div class=muted>月相</div><b>${S.moon}</b></div></div><div class=card><h2>设备状态</h2><div class=row><span>Wi‑Fi</span><b class="${S.wifi.connected?'ok':'bad'}">${S.wifi.connected?'已连接':'未连接'}</b></div><div class=row><span>最后更新</span><b>${S.lastUpdate}</b></div><div class=row><button class="btn primary" onclick=refreshWeather()>刷新天气</button><button class=btn onclick="demo('random')">随机预览</button></div></div>`;drawChart('rain',w.precip)}
function weather(){let days=S.forecast||[];q('#view').innerHTML=`<div class=tabs><button class=on>实时</button><button>24 小时</button><button>7 天</button></div><div class=card><h2>当前天气</h2><div class=row><div class=big>${Math.round(S.weather.temp)}°C</div><b>${esc(S.weather.label)}</b></div><div class=grid2><div class=muted>体感 ${Math.round(S.weather.feels)}°C</div><div class=muted>风速 ${S.weather.wind.toFixed(1)}m/s</div><div class=muted>云量 ${Math.round(S.weather.cloud)}%</div><div class=muted>阵风 ${S.weather.gust.toFixed(1)}m/s</div></div></div><div class=card><h2>未来 24 小时降水概率</h2><canvas id=rain class=mini></canvas></div><div class=card><h2>7 天天气预报</h2>${days.map((d,i)=>`<div class=forecast><b>${i?'+'+i:'今天'}</b><span>${esc(d.label)}</span><b>${Math.round(d.max)}°</b><span class=muted>${Math.round(d.min)}°</span><span class=tag>${d.pop}%</span></div>`).join('')}</div>`;drawChart('rain',S.weather.precip)}
function role(){let a=S.settings;let tabs=[['traveler','旅行者'],['dog','小狗'],['anim','动画'],['scene','场景预览']];q('#view').innerHTML=`<div class=tabs>${tabs.map(t=>`<button class="${roleTab==t[0]?'on':''}" onclick="roleTab='${t[0]}';role()">${t[1]}</button>`).join('')}</div><div id=roleBody></div>`;q('#roleBody').innerHTML=({traveler:roleTraveler,dog:roleDog,anim:roleAnim,scene:roleScene}[roleTab])(a)}
function roleTraveler(a){return `<div class=card><h2>服装模式</h2><div class=grid2><button class="btn ${a.outfitMode==0?'primary':''}" onclick="save({outfitMode:0})">自动根据天气</button><button class="btn ${a.outfitMode==1?'primary':''}" onclick="save({outfitMode:1})">手动固定服装</button></div></div><div class=card><h2>手动选择服装</h2><div class=grid3>${outfits.map(o=>`<button class="outfit ${a.manualOutfit==o[0]?'on':''}" onclick="save({outfitMode:1,manualOutfit:${o[0]}})"><div class=person>${o[2]}</div>${o[1]}</button>`).join('')}</div></div><div class=card><h2>旅行者动作</h2>${range('riderSpeed','踩踏速度',a.riderSpeed,60,140)}<div class=hint>建议：想更自然时，踩踏速度略慢、背景速度略快，会更像真的在前进。</div></div>`}
function roleDog(a){return `<div class=card><h2>小狗伙伴</h2>${sw('showDog','显示小狗',a.showDog,'白天跟跑，夜晚守护帐篷')}${range('dogSpeed','奔跑速度',a.dogSpeed,60,160)}${range('dogNightBright','夜晚亮度',a.dogNightBright,40,100)}</div><div class=card><h2>毛色风格</h2><div class=grid3>${dogTones.map(t=>`<button class="tone ${a.dogTint==t[0]?'on':''}" onclick="save({dogTint:${t[0]}})"><i style="background:${t[2]}"></i>${t[1]}</button>`).join('')}</div></div><div class=card><h2>小狗行为</h2><div class=hint>目前已支持奔跑速度、夜晚亮度和毛色。后续还可以继续加“兴奋程度、尾巴摆动、雨天跟随距离、夜晚睡姿”等更细的行为。</div></div>`}
function roleAnim(a){return `<div class=card><h2>动画速度</h2>${range('animationSpeed','整体速度',a.animationSpeed,60,140)}${range('backgroundSpeed','背景/路面速度',a.backgroundSpeed,60,150)}${range('riderSpeed','骑行者踩踏',a.riderSpeed,60,140)}${range('dogSpeed','小狗奔跑',a.dogSpeed,60,160)}</div><div class=card><h2>自然元素</h2>${sw('showWeatherEffects','天气粒子动画',a.showWeatherEffects,'雨、雪、雾、风沙、雷暴等')}${sw('showBirds','白天小鸟飞过',a.showBirds,'非极端天气下随机出现')}</div>`}
function roleScene(a){return `<div class=card><h2>场景预览</h2><div class=grid2>${scenes.map(s=>`<button class="scene ${s[2]}" onclick="demo('${s[0]}')"><div class=pic></div><b>${s[1]}</b><br><small class=muted>${s[3]}</small></button>`).join('')}</div></div><div class=card><h2>预览说明</h2><div class=hint>场景预览会直接改变开发板画面，用来测试天气动画、衣服、小狗、小鸟和昼夜效果。点“实时”会恢复网络天气。</div></div>`}
function status(){let a=S.settings;q('#view').innerHTML=`<div class=card><h2>状态栏与模块管理</h2><p class=muted>关闭后会从开发板屏幕上隐藏对应模块。</p>${sw('showWifi','Wi‑Fi 状态',a.showWifi)}${sw('showSunSchedule','日出日落昼夜曲线',a.showSunSchedule)}${sw('showPrecipitation','降水概率图',a.showPrecipitation)}${sw('showFeelsLike','体感温度',a.showFeelsLike)}${sw('showMoon','月相图',a.showMoon)}${sw('showHoliday','日本祝日信息',a.showHoliday)}${sw('showTemperature','气温显示',a.showTemperature)}</div>`}
function settings(){let a=S.settings;q('#view').innerHTML=`<div class=card><h2>系统设置</h2><div class=row><span>设备名称</span><b>${esc(S.device.name)}</b></div>${range('brightness','屏幕亮度',a.brightness,20,100)}${range('animationSpeed','动画速度',a.animationSpeed,60,140)}<div class=row><span>主题颜色</span><div class=colors>${['#2f80ed','#45bf80','#a46be8','#ff9f43','#e85d75'].map((c,i)=>`<button class=dot style="background:${c}" onclick="save({theme:${i}})"></button>`).join('')}</div></div></div><div class=card><button class="btn primary" onclick=refreshWeather()>立即刷新天气</button> <button class=btn onclick="demo('live')">恢复实时天气</button></div>`}
function wifi(){let list=S.savedWifi||[];q('#view').innerHTML=`<div class=card><h2>已保存的网络</h2>${list.map((n,i)=>`<div class=row><span>⌁ ${esc(n.ssid)} ${n.current?'<small class=ok>已连接</small>':''}</span><button class=btn onclick="api('/api/wifi/delete',{index:${n.index??i}}).then(load)">删除</button></div>`).join('')||'<p class=muted>暂无保存网络</p>'}</div><div class=card><h2>添加网络</h2><input id=ssid placeholder="Wi‑Fi 名称"><br><br><input id=pass placeholder="密码" type=password><br><br><button class="btn primary" onclick="api('/api/wifi/add',{ssid:q('#ssid').value,pass:q('#pass').value}).then(load)">添加 Wi‑Fi 网络</button></div><div class=card><button class="btn danger" onclick="if(confirm('清空所有已保存 Wi‑Fi？'))api('/api/wifi/clear',{}).then(load)">清空所有网络</button></div>`}
function about(){q('#view').innerHTML=`<div class=card><h2>关于设备</h2><div class=row><span>设备型号</span><b>${esc(S.device.name)}</b></div><div class=row><span>固件版本</span><b>${S.device.firmware}</b></div><div class=row><span>网页版本</span><b>${S.device.web}</b></div><div class=row><span>空闲内存</span><b>${S.device.heap} B</b></div><div class=row><span>编译时间</span><b>${S.device.build}</b></div></div><div class=card><button class="btn primary" onclick="location.reload()">重新加载后台</button> <button class=btn onclick=reboot()>重启设备</button></div>`}
load();setInterval(load,9000);
</script></body></html>
)HTML";
